name: Daily Submodule Update

on:
  schedule:
    - cron: '0 8 * * *' # Runs at 6:00 AM UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up environment
      run: chmod a+x updateSubmodules.sh

    - name: Update submodules
      run: ./updateSubmodules.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'Antonius Torode'
        git config --global user.email 'torodean@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
        git add -A
        git commit -m "Automatic Submodule update."
        git push origin main
      env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
