name: Daily Submodule Update

on:
  schedule:
    - cron: '0 8 * * *' # Runs at 6:00 AM UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up environment
      run: chmod a+x update_submodules.sh

    - name: Update submodules
      run: ./update_submodules.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
